apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-volume
  namespace: ucandoit
spec:
  storageClassName: uploads
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/opt/k3dvolume/media'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-volume-claim
  namespace: ucandoit
spec:
  storageClassName: uploads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi